### PR TITLE
Removed the debugging call

### PR DESCRIPTION
**Pull request by stof**
Displaying a message in the console each time the file is loaded is not nice for a prod environment (and even less nice in IE8 which will trigger an exception on the console call as it does not have the console object)

### CODE REVIEW

**Comment by fguillen** [comment]
A middle solution between your needs and my ones: https://github.com/fguillen/MDMagick/commit/4041e7a21cc9045deaa0b0f4df66e6a768c79b38

**Comment by stof** [comment]
@fguillen I think it should be silent by default. Adding a console log each time the file is loaded looks useless to me.

**Comment by fguillen** [comment]
Now you have the possibility to silent this log adding:

```
<script> window.MDM_SILENT = true; </script>
```

Before you load the file.

f.

On Wed, Dec 12, 2012 at 1:01 AM, Christophe Coevoet
notifications@github.com wrote:

> @fguillen I think it should be silent by default. Adding a console log
> each time the file is loaded looks useless to me.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Fernando Guillén
Freelance Web Developer
http://www.fernandoguillen.info
http://spainrb.org/fernando-guillen

**Comment by stof** [comment]
@fguillen sure, but I think the _default_ should be to be silent. The only reason I see to need a debug call indicating the library is loaded is debugging MDMagick, so I don't see it useful as a default behavior. So to me, it should be the opposite (doing the debug call only when you set a variable before that)

**Comment by fguillen** [comment]
I agree that should be a way to _mute_ the MDMagick plugin, and this is what I offer in the above commit. 

About if the default behavior of a JS plugin should be to show "none" information in the console I think this is a matter of taste.

In my opinion every JS plugin should show a minimal information in the "debug" console _by default_.  At the end it is a "console" and if you open it you want to see stuff there, I can't think in any computer program that doesn't show any information at all in "it's console" by default.

Just check that the only log MDMagic is putting out _by default_ is `loading MDMagick v0.0.3...`, it is not like it is sending hundred of _debug_ messages to the console. 

Interesting topic by the way :)

**Comment by stof** [comment]
@fguillen There is another argument for being silent by default: currently, the library triggers a JS error by default in IE (which does not have the console object).

And I could agree that the console is a developper tool. But then, `loading MDMagick` is not the most relevant part of the library IMO. You don't log anything when the library actually does something, only when the browser successfully parsed the file.

**Comment by fguillen** [comment]
The issue with the IE can be solved with the:

```
<script> window.MDM_SILENT = true; </script>
```

About if the message `loading MDMagick` is important or not is
relative, for me it is, due this way I can know the script has been
properly integrated. Believe me that this message has saved me a lot
of time in speculations.

**Pull request closed without merging**
